In [1]:
import pandas as pd
pd.set_option('display.max_Colwidth',None)

In [2]:
df = pd.read_csv('translated_hindi_dataset.csv')

In [3]:
df.head()

,text,Label_binary,translated_text
0,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर रोका #INDvBAN #CWC19",0,"Great comeback by Bangladesh, restricted India to 314 runs #INDvBAN #CWC19"
1,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांतीदूत के साथ कुछ होगा सब #रंडीरोना शुरू कर देंगे,1,"All the whores are busy watching the dance. As soon as something happens with a #peacemaker, all the #whores will start crying."
2,तुम जैसे हरामियों के लिए बस जूतों की कमी है शुक्र कर अभी तुम्हारी लिंचिंग हुई नहीं है हिंदुओं के जागने की देर है सच में होगी अभी तो तुम जैसे हरामी सुवर ड्रामा बनाएं हो सुवर कहीं का मौलाना। तुम जैसे हरामियों कुत्ते की मौत मारना चाहिए सुवर जैसी शक्ल रंडी की औलाद सुवर कहीं का ।।।।,1,"There is just shortage of shoes for bastards like you. Thank God you have not been lynched yet. It is too late for the Hindus to wake up. It will actually happen now. Bastards like you have created a pig drama, some Maulana of a pig. Bastards like you, the dog should be killed, the pig-like face, the son of a whore, the pig from somewhere."
3,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत मिलने की खुशी में एक समर्थक ने इंदौर में हर्ष फायरिंग की #AkashVijayvargiya https://abpnews.abplive.in/india-news/celebratory-firing-outside-bjp-mla-akash-vijayvargiya-office-in-indore-1157241 …",0,"BJP MLA Akash Vijayvargiya released from jail, in celebration of getting bail, a supporter opened fire in Indore #AkashVijayvargiya https://abpnews.abplive.in/india-news/celebratory-firing-outside-bjp-mla-akash-vijayvargiya-office-in-indore-1157241…"
4,"चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर्शन, तेजस्वी यादव नदारद #biharencephalitisdeaths https://abpnews.abplive.in/bihar-news/aes-deaths-rjd-protest-in-vidhan-sabha-campus-but-tejashwi-yadav-was-not-present-1158748 … (रिपोर्ट- @kumarprakash4u )",0,"Chamki fever: RJD's protest in the assembly campus, Tejashwi Yadav missing #biharencephalitisdeaths https://abpnews.abplive.in/bihar-news/aes-deaths-rjd-protest-in-vidhan-sabha-campus-but-tejashwi-yadav-was-not-present-1158748… (Report- @kumarprakash4u)"

In [4]:
# Cleanup / preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4665 entries, 0 to 4664
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             4665 non-null   object
 1   Label_binary     4665 non-null   int64
 2   translated_text  4655 non-null   object
dtypes: int64(1), object(2)
memory usage: 109.5+ KB

In [5]:
df.isnull().sum()

text                0
Label_binary        0
translated_text    10
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.dropna(subset = 'translated_text')

In [8]:
df.isnull().sum()

text               0
Label_binary       0
translated_text    0
dtype: int64

In [9]:
df['Label_binary'].value_counts()

Label_binary
1    2465
0    2190
Name: count, dtype: int64

In [10]:
 "Unnamed : 0" in df.columns

False

In [11]:
df['text_length'] = df['translated_text'].astype(str).apply(len)
df['text_length'].describe()

count    4655.000000
mean      168.645542
std        91.939942
min         6.000000
25%        93.000000
50%       151.000000
75%       238.000000
max       719.000000
Name: text_length, dtype: float64

In [12]:
# explain here the .describe() analysis

## Lowercasing

In [13]:
df['translated_text'] = df['translated_text'].str.lower()

Here we will check about the presence of tags or url in the dataset

In [14]:
df[df['translated_text'].str.contains(r'https?://\S+|www\.\S+|@\w+|#\w+|<[^>]+>', na = False)].shape

(2027, 4)

In [15]:
df['clean_text'] = df['translated_text'].str.replace(r'https?://\S+|www\.\S+|@\w+', '', regex=True)
df['clean_text'] = df['clean_text'].str.replace(r'#', '', regex=True)

In [16]:
df.sample(10 , random_state = 42)

,text,Label_binary,translated_text,text_length,clean_text
1618,बिहार में चमकी बुखार के प्रकोप पर सीएम नीतीश कुमार LIVE देखने के लिए नीचे लिंक पर क्लिक करें: https://www.youtube.com/watch?v=ufqXGYKZEY8 …,0,click on the link below to watch cm nitish kumar live on the outbreak of chamki fever in bihar: https://www.youtube.com/watch?v=ufqxgykzey8…,140,click on the link below to watch cm nitish kumar live on the outbreak of chamki fever in bihar:
1184,Phla kadam hi lad khadata hua nazar aara hai....seat hi bchaalo phle apni,0,"at every step, i look at what i have eaten....save your seat.",61,"at every step, i look at what i have eaten....save your seat."
2183,निशांत वर्मा वेश्यावृत्ति की उपज है या गटर के सुअर का औलाद।।,1,is nishant verma the product of prostitution or the offspring of a gutter pig?,78,is nishant verma the product of prostitution or the offspring of a gutter pig?
3534,"क्यों सुअर , कभी तू भी काफिर ही था , वो तो औरंजेब ने लूटी अस्मत 5/7 पीढी पहले , डर के तेरे बाबा , पड़ बाबे मुल्ला बन बैठे , अम्मी से पूछ वो सारा सच बताएगी",1,"why pig, once upon a time you were also an infidel, it was auranzeb who looted the honor 5/7 generations ago, out of fear your father became a mullah, ask your mother, she will tell you the whole truth.",202,"why pig, once upon a time you were also an infidel, it was auranzeb who looted the honor 5/7 generations ago, out of fear your father became a mullah, ask your mother, she will tell you the whole truth."
634,"दंगाई मस्त, पुलिस पस्त! देखिए #Dangal @sardanarohit के साथ, शाम 5 बजे, सिर्फ आजतक पर",0,"rioters are happy, police are defeated! watch #dangal with @sardanarohit at 5 pm only on aaj tak",97,"rioters are happy, police are defeated! watch dangal with at 5 pm only on aaj tak"
415,लोग क्या कहेंगे यह 'सोचकर' जीवन जीते हैं भगवान क्या कहेंगे क्या कभी.... इसका विचार किया ?....!!! शुभ रात्रि जय श्री कृष्णा,0,we live our lives thinking about what people will say. have you ever thought about what god will say?...!!! good night jai shri krishna,136,we live our lives thinking about what people will say. have you ever thought about what god will say?...!!! good night jai shri krishna
3698,Amritsar में @HardeepSPuri जी को जिताना है। एक नंबर का बटन दबाना है। कमल का फूल खिलाना है। @narendramodi जी को प्रधानमंत्री बनाना है। #PhirEKBaarModiSarkaar @BJP4Punjab,0,@hardeepspuri ji has to win in amritsar. have to press a number button. have to feed lotus flower. @narendramodi ji has to be made the prime minister. #phirekbaarmodisarkaar @bjp4punjab,191,ji has to win in amritsar. have to press a number button. have to feed lotus flower. ji has to be made the prime minister. phirekbaarmodisarkaar
33,अमित शाह से बाद में फिर तू पूछेगी यह क्या कर दिया रंडी,1,later you will ask amit shah what he did whore.,47,later you will ask amit shah what he did whore.
791,प्रदेश अध्यक्ष श्री @ManojTiwariMP जी की धन्यवाद यात्रा। #ThankYouDelhi,0,thank you visit of state president shri @manojtiwarimp. #thankyoudelhi,70,thank you visit of state president shri . thankyoudelhi
3828,"देश मे 2014 के बाद बम्ब धमाके होना बंद हो गए है। Modi पुलवामा, छत्तीसगढ़, उड़ी, गढ़चिरौली, पठानकोट मे BJP वालो ने दीवाली मनाई थी क्या??? जवानो के नाम पे वोट मांग कर #नीच राजनीति बन्द करो मोदी जी उनके सुरक्षा व्यवस्था का इंतेजाम करो... @INCIndia #MaafiMaangoModi",1,"bomb blasts have stopped in the country after 2014. modi: did bjp people celebrate diwali in pulwama, chhattisgarh, uri, gadchiroli, pathankot??? stop #lowpolitics by asking for votes in the name of soldiers, modi ji, make arrangements for their security... @incindia #maafimaangomodi",287,"bomb blasts have stopped in the country after 2014. modi: did bjp people celebrate diwali in pulwama, chhattisgarh, uri, gadchiroli, pathankot??? stop lowpolitics by asking for votes in the name of soldiers, modi ji, make arrangements for their security... maafimaangomodi"

In [17]:
# Puntuation handeling 

import string

print(string.punctuation)
exclude = string.punctuation

def punctuation_remove(text):
    return text.translate(str.maketrans('','',exclude))

df['clean_text'] = df['clean_text'].apply(punctuation_remove)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [18]:
# There were some hindi words in it so i have replaced those with spaces 

df['clean_text'] = df['clean_text'].str.replace(r'[^a-zA-Z\s]', ' ', regex=True)

## Check for Emojis

In [19]:
df[df["clean_text"].str.contains(r"[\U00010000-\U0010ffff]" , na = False)].shape
# No emoji is found

(0, 5)

## Stop Words

In [20]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

stopwords = set(ENGLISH_STOP_WORDS)
stopwords.discard('no')
stopwords.discard('not')
stopwords.discard('never')
stopwords.discard('nor')

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word  not in stopwords])

df['clean_text'] = df['clean_text'].apply(remove_stopwords)

## Lemmatizer

In [21]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [22]:
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["Content_lemma"] = df["clean_text"].apply(lemmatize_text)

df.sample(10,random_state = 42)

## Model Trianing begin........

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [24]:
# splitting of the data
x = df['Content_lemma']
# x = df['Content_lemma']
y = df['Label_binary']
x_train,x_test,y_train,y_test = train_test_split(
    x,y ,test_size = 0.2 , random_state = 42
)

In [25]:
# vectorisation by  Tf-idf with n-gram

tfidf = TfidfVectorizer(
    ngram_range = (1,3),
    max_features = 15000,
    min_df = 3,
    max_df = 0.85
)

x_train_tfidf = tfidf.fit_transform(x_train)
x_test_tfidf = tfidf.transform(x_test)

In [26]:
model = LogisticRegression(max_iter = 1000)
 
model.fit(x_train_tfidf , y_train)

LogisticRegression(max_iter=1000)

In [27]:
y_pred = model.predict(x_test_tfidf)
print("Classification report for logistic regression is :\n",classification_report(y_test , y_pred))

Classification report for logistic regression is :
               precision    recall  f1-score   support

           0       0.78      0.79      0.79       437
           1       0.81      0.81      0.81       494

    accuracy                           0.80       931
   macro avg       0.80      0.80      0.80       931
weighted avg       0.80      0.80      0.80       931

In [28]:
# INPUT PIPELINE

from deep_translator import GoogleTranslator
translator = GoogleTranslator(source = 'auto', target = 'en')
test_statements = [
    "कुत्ते की तरह भौंकना बंद कर, तेरी कोई औकात नहीं है।",
    "इस गद्दार को देश से निकाल देना चाहिए, यह देशद्रोही है।",
    "तुम ल��ग एकदम गवार और जाहिल हो, तुमको अकल नहीं है।",
    "शर्म कर बे, तुम जैसों को तो चौराहे पर पीटना चाहिए।",
    "बकवास बंद कर बेवकूफ, तेरा दिमाग सड़ गया है।",
    "तुम जैसे बेवकूफों को तो जेल में डाल देना चाहिए।",
    "आज मौसम बहुत अच्छा है, चलो कहीं घूमने चलते हैं।",
    "तू एक नंबर का झूठा और नीच इंसान है।",
    "भाई, क्या तुम मुझे कल की मीटिंग का समय बता सकते हो?",
    "मैं किसी से नफरत नहीं करता, सब मेरे दोस्त हैं।",
    "इन गद्दारों को देश से मार भगाओ।",
    "तुम बहुत काले हो"
]
test_state = []
for text in test_statements:
    english = translator.translate(text)
    test_state.append(english)
inputs = tfidf.transform(test_state)
model.predict(inputs)

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1])